// SECTION API test environment
// ANCHOR This POST-Requests tests the registration interface
POST http://localhost:1000/openRoute/register
Content-Type: application/json

{
	"username": "hava",
	"password": "hava",
	"email": "hava@tfbern.ch",
	"firstname": "Halid",
	"lastname": "Vakuyev",
	"age": 20,
	"height": 180,
	"weight": 75,
	"equipment": false,
	"color": "amber"
}

###

// ANCHOR This POST-Requests tests the login interface
POST http://localhost:1000/openRoute/login
Content-Type: application/json


{
	"username": "hava",
	"password": "hava"
}

###

// ANCHOR This POST-Requests tests the refresh interface
POST http://localhost:1000/openRoute/refresh
Content-Type: application/json


{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhdmEiLCJpYXQiOjE1OTE2MTU3NTJ9.72f--mVPzZ7s8qEmecKRqzaWkInDbRyqgsfEkRzJMYU"
}

###

// ANCHOR This GET-Requests tests, if users have access to all exercises
GET http://localhost:2000/protectedRoute/exercises
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTE2MTU3NzQsImV4cCI6MTU5MTYxNTc4OX0.VjFWDuBZT93XHKoNFyse1L-vGoifL7-1u6Mro4l29rs


###

// !SECTION