// SECTION API test environment
// ANCHOR This POST-Requests tests the registration interface
POST http://localhost:1000/openRoute/register
Content-Type: application/json

{
	"username": "hava",
	"password": "hava",
	"email": "hava@tfbern.ch",
	"firstname": "Halid",
	"lastname": "Vakuyev",
	"age": 20,
	"height": 180,
	"weight": 75,
	"equipment": false,
	"color": "amber"
}

###

// ANCHOR This POST-Requests tests the login interface
POST http://localhost:2000/openRoute/login
Content-Type: application/json


{
	"username": "hava",
	"password": "hava"
}

###

// ANCHOR This POST-Requests tests the refresh interface
POST http://localhost:1000/openRoute/refresh
Content-Type: application/json


{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhdmEiLCJpYXQiOjE1OTE1NzI2ODZ9.BUeaUm5OOUVlAuCy9VMmGeBTehHsPN_HyIJPPxp64Zs"
}

###

// ANCHOR This GET-Requests tests, if users have access to all exercises
GET http://localhost:2000/protectedRoute/exercises
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhdmEiLCJpYXQiOjE1OTE1NzI4MTQsImV4cCI6MTU5MTU3MjgyOX0.g0bQz1_SgBw-d21ORtm9Kj0kinyrdi4mxpbAs7vwJxo"


###

// !SECTION